# Generated by Django 3.1.5 on 2021-01-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmeeting',
            name='question',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='classmeeting',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard.school'),
        ),
    ]
