# Generated by Django 3.1.5 on 2021-01-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_classmeeting_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassMeeting',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
