# Generated by Django 3.1.5 on 2021-01-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboard', '0006_auto_20210111_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_cm', models.IntegerField(default=0)),
                ('year_cm', models.IntegerField(default=0)),
                ('term_cm', models.IntegerField(default=0)),
                ('month_cm', models.IntegerField(default=0)),
                ('first_post', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard.school')),
            ],
        ),
    ]
