# Generated by Django 3.1.5 on 2021-01-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_classmeeting_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='MD5_Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
